[project]
name = "cs336-workspace"
version = "0.1.0"
description = "Shared environment for CS336 assignments"
requires-python = ">=3.10,<3.13"
dependencies = [
    "cs336-basics",
    "cs336-systems",
]

[tool.uv]
package = false
environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]

[tool.uv.sources]
cs336-basics = { path = "assignment1-basics", editable = true }
cs336-systems = { path = "assignment2-systems", editable = true }
